### ISSUE TITLE
В чем задумка объектов enum (TextAdFieldEnum)? Как их использовать?

### ISSUE THREAD

**Issue by vmulaev** [biplane/yandex-direct#1]
Привет, смотрю апи директа, каким образом передать параметр в
Biplane\YandexDirect\Api\V5\Contract\TextCampaignSetting->setOption

Все время вылетает ошибка, если убрать проверку типа все работает
public function setOption($value)

В чем задумка объектов enum (TextAdFieldEnum)? Как их использовать?

**Comment by yethee** [comment]
Привет.

Весь код для контрактов данных генерируется автоматически, на основании WSDL.
То, что в некоторых сеттерах требует объект, вместо строки, это ошибка генерации, к сожалению.

> В чем задумка объектов enum (TextAdFieldEnum)? Как их использовать?

Использование констант делает код более читаемым, снижает вероятность опечатки и т.п..

По поводу примера с `TextCampaignSetting`, код мог бы выглядеть примерно так:

```php
$contract = TextCampaignSetting::create()
    ->setOption(TextCampaignSettingsEnum::ENABLE_AUTOFOCUS);
```

**Comment by yethee** [comment]
@vmulaev обновитесь до последней версии. Убрал ошибочный type hinting, выше приведенный пример кода сейчас должен работать как ожидается.

**Comment by vmulaev** [comment]
Супер, благодарю!
