### ISSUE TITLE
Ошибка при работе с объявлениями и группами ID которых превышает размер integer

### ISSUE THREAD

**Issue by tiu-85** [biplane/yandex-direct#10]
Если ID объявления или группы превышает максимальный размер integer, при выполнении методов api мы получаем ошибку. Все ID передаются в виде числа 2147483647 и операции не выполняются корректно. Видимо через soap необходимо передавать массив строк, которые представляют из себя числа с типом long вместо массива чисел.

**Comment by tiu-85** [comment]
![111](https://user-images.githubusercontent.com/11041849/43897471-857a6ad8-9bf5-11e8-872a-f0423eb310f6.png)
![222](https://user-images.githubusercontent.com/11041849/43897472-85a1e946-9bf5-11e8-97e2-a2a328cef700.png)

**Comment by yethee** [comment]
В 32-битной версии PHP размер типа `int` четыре байта, поэтому происходит округление. В этом случае с числами можно работать как со строками. 

Либо же перейти на 64-битную версию, где тип `int` - 8 байт.

Похожий тикет #9
