### ISSUE TITLE
Не проходит валидация по XSD-схеме при 

### ISSUE THREAD

**Issue by croissant-sama** [biplane/yandex-direct#12]
В https://github.com/biplane/yandex-direct/issues/11 были добавлены новые параметры в `\Biplane\YandexDirect\Api\V5\Report\ReportDefinitionBuilder`. После добавления параметра запрос не проходит валидация на соответствие  XSD-схеме.
Похоже проблема методе `\Biplane\YandexDirect\Api\V5\Report\ReportDefinitionBuilder::buildDocument` в порядке добавления узлов.

**Comment by yethee** [comment]
Да, действительно, новые параметры ломали XML. Исправлено.

Спасибо, что сообщили об ошибке.
