### ISSUE TITLE
Ошибка в формировании финансового токена.

### ISSUE THREAD

**Issue by giv13** [biplane/yandex-direct#13]
Здравствуйте.

Выдержка из документации:
Параметр finance_token необходимо сформировать путем шифрования SHA256. Шифруется строка, полученная конкатенацией следующих подстрок:
- мастер-токен;
- номер операции (параметр operation_num);
- название вызываемого финансового метода;
- название операции (для метода AccountManagement (Live));
- нормализованный логин пользователя, от имени которого делается запрос к API.

Но у вас название операции для метода AccountManagement не прибавляется к названию вызываемого финансового метода, а заменяет его. То есть в файле `src/Api/SoapClientV4.php` на 72 строке должно быть не `$usedMethod = $arguments[0]->getAction();`, а `$usedMethod .= $arguments[0]->getAction();`

**Comment by yethee** [comment]
Спасибо, за информацию. Ошибку исправил. Изменение доступно в новой версии **4.7.1**
