### ISSUE TITLE
Как получить units после вызова метода

### ISSUE THREAD

**Issue by feamir** [biplane/yandex-direct#17]
Как правильно по задумке получать **units** после вызова soap метода?

Например после вызова setBid:

`$res = $clientUser->getBidsService()->set($bidder);`

В _PostCallEvent_ в _invoke()_ units передаются, как их достать? Или этот момент не реализован?

**Comment by yethee** [comment]
Все сервисы для API 5 поддерживают метод [`getUnits()`](https://github.com/biplane/yandex-direct/blob/be7aa50a8cc7be9a18fd8320ecea1270f926f76d/src/Api/SoapClientV5.php#L63-L79). То есть, для вашего примера можно решить вопрос примерно так:

```php
$service = $clientUser->getBidsService();
$response = $service->set($bidder);
$units = $service->getUnits();
```

> В PostCallEvent в invoke() units передаются, как их достать? Или этот момент не реализован?

Да, через событие так же можно получить информацию о баллах. Для этого нужно реализовать обработчик и зарегистрировать его в `EventDispatcher`.

```php
class MyEventListener implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
         return [
             Events::AFTER_REQUEST => 'onAfterRequest',
         ];
    }

    public function onAfterRequest(PostCallEvent $event): void
    {
        // $event->getUnits(); 
    }
}

$clientUser->getEventDispatcher()->addSubscriber(new MyEventListener());
```

Расширение с помощью событий предоставляет возможность решить какие-то моменты централизованно. Например, реализовать логирование обращений к API.

**Comment by feamir** [comment]
@yethee Спасибо большое!
