### ISSUE TITLE
Sum и Balance в Funds

### ISSUE THREAD

**Issue by Neolot** [biplane/yandex-direct#2]
Добрый день!
Спасибо за библиотеку, очень помогает.
Подскажите, как получить баланс на сабаккаунте по каждой кампании?
Делаю вот такой запрос, но в ответе полей Sum и Balance в Funds нет, хотя в API есть.
```php
$request_selection_criteria = CampaignsSelectionCriteria::create()
	->setIds(array())
	->setStates(array('ON'));
$request = GetCampaignsRequest::create()
	->setSelectionCriteria($request_selection_criteria)
	->setFieldNames(array(
		CampaignFieldEnum::ID,
		CampaignFieldEnum::NAME,
		CampaignFieldEnum::FUNDS,
		CampaignFieldEnum::CURRENCY,
		CampaignFieldEnum::CLIENT_INFO
	));
$campaigns_data = $subuser->getCampaignsService()->get($request);

**Comment by yethee** [comment]
Привет!

Если для аккаунта подключен общий счёт, то баланс по отдельной кампании недоступен.

Определить, подключен общий счёт или нет, можно с помощью метода `Biplane\YandexDirect\Api\V5\Contract\FundsParam::getMode()`, который вернет строку `SHARED_ACCOUNT_FUNDS` в первом случае, иначе - `CAMPAIGN_FUNDS`. 

Примерно такая логика:

```php
/** @var \Biplane\YandexDirect\Api\V5\Contract\CampaignGetItem $item */
foreach ($campaigns_data->getCampaigns() as $item) {
    $funds = $item->getFunds();

    if ($funds->getMode() === CampaignFundsEnum::CAMPAIGN_FUNDS) {
        /** @var \Biplane\YandexDirect\Api\V5\Contract\CampaignFundsParam $params */
        $params = $funds->getCampaignFunds();

        // $params->getBalance();
        // $params->getSum();
    }
}
```

**Comment by Neolot** [comment]
Спасибо, с этим понятно, а как получить баланс субаккаунта, если он общий?
Мне нужно получить баланс средств на субаккаунте. В API 4.0 его можно было получить с помощью  GetCampaignsListFilter, там было поле Rest.

**Comment by Neolot** [comment]
Разобрался, баланс получается через getBalance API 4.0
Спасибо за помощь!

**Comment by yethee** [comment]
Пожалуйста. :)

Нужно учитывать, что при подключенном общем счёте у всех кампаний, получаемых методом [GetBalance](https://tech.yandex.ru/direct/doc/dg-v4/live/GetBalance-docpage/), остаток (`Rest`) будет совпадать. Думаю, можно взять среднее арифметическое остатков по кампаниям. Это должно отражать более-менее актуальное значение баланса по аккаунту, с учетом возвратов по отдельным кампаниям.

Мне кажется, Вам больше подойдет [AccountManagement.Get](https://tech.yandex.ru/direct/doc/dg-v4/live/AccountManagement_Get-docpage/), если нужно получить общий баланс по аккаунту.

**Comment by Neolot** [comment]
О, а за это отдельное спасибо! То, что нужно)
