### ISSUE TITLE
SoapClientV5 support override stream_context

### ISSUE THREAD

**Issue by dmachehin** [biplane/yandex-direct#20]
Need to specify a proxy or certificate.

`SoapClientV5` does not allow to override the option `stream_context`

I suggest a simple fix for `SoapClientV5`:
```php
if (isset($options['stream_context']) && is_resource($options['stream_context'])) {
 $stream_context_options = stream_context_get_options($options['stream_context']);
} else {
 $stream_context_options = [];
}

$stream_context_options['http']['header'] = $this->createHttpHeaders($user);

$options['stream_context'] = stream_context_create($stream_context_options);
```

**Comment by dmachehin** [comment]
Or maybe changed method getProxy in class `User` to protected for access to soapclient->_streamcontext

**Comment by yethee** [comment]
Sorry, for a noise with changes of issue status.

I created PR to fix this issue. The PR adds ability to define the stream context through the User object.

> Need to specify a proxy or certificate.

To set HTTP proxy you can use soap options, `proxy_host`, `proxy_port`, `proxy_login` and `proxy_password`. For example:

```php
new User([
    'soap_options' => [
        'proxy_host' => '127.0.0.2',
        'proxy_port' => 8888,
    ]
]);
```

**Comment by dmachehin** [comment]
@yethee After pull, i'm get error `OAuth token is missing` (not set soap_options in `User`)
In request missing headers...
```
POST /v5/dictionaries HTTP/1.1
Host: soap.direct.yandex.ru
Connection: Keep-Alive
User-Agent: PHP-SOAP/7.2.24
Content-Type: text/xml; charset=utf-8
SOAPAction: "http://api.direct.yandex.com/v5/dictionaries/get"
Content-Length: 303



<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://api.direct.yandex.com/v5/dictionaries"><SOAP-ENV:Body><ns1:GetRequest><DictionaryNames>Constants</DictionaryNames></ns1:GetRequest></SO"...
[critical] Call Dictionaries:get completed with exception Biplane\YandexDirect\Exception\ApiException: OAuth token is missing
```

**Comment by dmachehin** [comment]
@yethee Need revert `return implode("\r\n", $headers);` in createHttpHeaders

**Comment by yethee** [comment]
@dmachehin thanks for feedback. Indeed, `SoapClient` does not send headers when these are defined as an array at stream context (known issue https://github.com/facebook/hhvm/issues/8047).

Can you confirm, that #21 solves your issue?

**Comment by yethee** [comment]
> Or maybe changed method getProxy in class `User` to protected for access to soapclient->_streamcontext

I think, we should deprecate ability to setup `soap_options` from user-land code or restrict by subset options (proxy, cache, timeouts). Because some options may be conflict with SOAP server, and we can not override these. As well as we have the Reports service, which does not use SOAP.
Instead, need to think about generic options of proxy and other transport related settings.

Can you explain for what you need to additional setup `stream_context` for SOAP client? To configure HTTP proxy or something else?

**Comment by dmachehin** [comment]
@yethee stream_context need for set ssl.verify_perr=false (ssl bug in old centos 6) and maybe later set bind ip or proxy.

P.S. You have plans for using JSON instead SOAP?

**Comment by yethee** [comment]
> You have plans for using JSON instead SOAP?

No such plans to migrate to JSON implementation. It will be required to implement complex logic for serialization/deserialization and many code for data contracts. While for SOAP we can use schema (WSDL) for auto-generate code.
Another solution to reuse auto-generated code of contracts. In this case we need to implement logic for serialization. But it requires to support JSON and SOAP.

**Comment by dmachehin** [comment]
@yethee 
> Can you confirm, that #21 solves your issue?

Yes, thx!

**Comment by yethee** [comment]
New release `4.14.0` available.
