### ISSUE TITLE
ApiException new constant with code=3000

### ISSUE THREAD

**Issue by dmachehin** [biplane/yandex-direct#24]
`(code: 3000): Аккаунт пользователя блокирован`

**Comment by yethee** [comment]
Сейчас можно признать, что добавление констант с кодами ошибок API в класс `ApiException` было неудачным решением. Яндекс.Директ API развивается и поддерживать список кодов ошибок в актуальном состоянии достаточно накладно.
В следующей мажорной версии (5.x) планирую удалить все константы из `ApiException`.

Можно на уровне приложения добавлять константы для тех кодов, которые обрабатываются.
