### ISSUE TITLE
Новые именования классов в EventDispatcher v5

### ISSUE THREAD

**Issue by rik43** [biplane/yandex-direct#30]
на свою голову обновился до посл версии. 

ваш класс \Biplane\YandexDirect\Event\PreCallEvent
использует 
`use Symfony\Component\EventDispatcher\Event;`

а в EventDispatcher v5 его переименовали 
`\Symfony\Contracts\EventDispatcher\Event`

у меня установилась:
`            "name": "symfony/event-dispatcher",
            "version": "v5.1.7",`

**Comment by rik43** [comment]
обидно еще и то что `biplane/yandex-direct@dev-symfony-5` вы тоже удалили :( 
не вернуться

**Comment by yethee** [comment]
Класс `Biplane\YandexDirect\Event\PreCallEvent` наследуется от [`BaseEvent`](https://github.com/biplane/yandex-direct/blob/4.19.0/src/Event/BaseEvent.php). Последний отвечает за совместимость между `symfony/event-dispatcher` 5.* и предыдущими версиями.

В какой момент ошибка возникает?

В одном из своих проектов обновил пакет до `4.19.0`. Полет нормальный.

```
$ composer show | Select-String -Pattern "yandex-direct","event-dispatcher"

biplane/yandex-direct                          4.19.0  PHP library for Yandex.Direct API
psr/event-dispatcher                           1.0.0   Standard interfaces for event handling.
symfony/event-dispatcher                       v5.1.7  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts             v2.2.0  Generic abstractions related to dispatching event
```
```

**Comment by yethee** [comment]
@rik43 удалось решить проблему?

**Comment by rik43** [comment]
Добрый день. пробовал тогда еще один раз, но снова те же ошибки. 
к сожалению не было больше времени этим заниматься. 
откатился назад.

**Comment by rik43** [comment]
тикет наверное можно закрыть пока. если непонятно что делать. 
если появится время - попробую снова - отпишусь подробнее.

**Comment by yethee** [comment]
Если будет понятно, как воспроизвести проблему, можно будет открыть тикет.
