### ISSUE TITLE
php 8

### ISSUE THREAD

**Issue by madmages** [biplane/yandex-direct#32]
Уже есть php 8. 
В этой библиотеке нет поддержки восьмерки, а хотелось бы.
Можно ожидать восьмерку и когда ?

**Comment by yethee** [comment]
Изначально были мысли актуализировать код (отказаться от зависимостей `symfony/event-dispatcher`, `guzzlehttp/guzzle` и др) и попутно обновить ограничения по версии PHP, но свободного времени сейчас не много, к сожалению.

Наверное, можно сделать два этапа.

1. В версии 5.x обновить ограничения для PHP
2. В версии 6.x реимплементация.

**Comment by madmages** [comment]
Может есть смысл пока что просто добавить 8 в composer.json и завернуть это в минорную версию ?
или этого будет не достаточно ?

**Comment by yethee** [comment]
Сейчас есть зависимости (например, `phpunit:^5.7`), которые будут конфликтовать. В CI будут ошибки.
PHP 8.0 пока нигде не эксплуатирую, не могу проверить совместимость кода с этой версией PHP.

**Comment by yethee** [comment]
Создал PR #34, который добавляет поддержку PHP 8, но для следующей мажорной версии. Где будут изменения без обратной совместимости с 4.x:

* `ApiException` наследуется от `RuntimeException`, а не `Biplane\YandexDirect\Exception\RequestException`
* Из `ApiException` удалены все константы с кодами ошибок
* Удален `Invoker`, который из коробки предоставлял логику повторного вызова методов при временных ошибках
* Нет реализации кастомного провайдера номера операции для финансовых методов (#25). *Нужно будет реимплементировать.*

Ветка `master` к релизу пока не готова, но можно создать тег для бета-версии.

**Comment by yethee** [comment]
Добавил тег `5.0.0-beta1`. По идее, должно быть совместимо с `4.0`, за исключением типов исключений. Подробнее в [changelog](https://github.com/biplane/yandex-direct/blob/3d2d95cfd81be184e27e5ee7c67b8ee90e424e12/CHANGELOG.md)

**Comment by madmages** [comment]
круто! через какое-то время у меня будет еще одна итерация перехода на 8, посмотрю на происходящее подробнее.

**Comment by dmachehin** [comment]
@yethee Почему удалили `Invoker` довольно удобное было с ним?

**Comment by Subszerro** [comment]
@yethee А когда будет добавлен тип PAY_FOR_CONVERSION_CRR в Biplane\YandexDirect\Api\V5\Contract\TextCampaignSearchStrategyTypeEnum?

**Comment by yethee** [comment]
> @yethee Почему удалили `Invoker`? Удобно было с ним

Нет уверенности, что это действительно полезный функционал на уровне библиотеки. Но не смотря на сомнения, не так давно был коммит с альтернативной логикой для 5.*. Пока в отдельной ветке, #35

Вы на уровне приложения как-то ошибки API обрабатываете?

**Comment by dmachehin** [comment]
@yethee 
Сейчас ошибки обрабатываем только в редких случаях (валидация например, когда текст объявления к примеру может быть кривой)
Для временных ошибок (которые часто бывают, например при проблемах с каналом и т.п.), отлично Invoker подходит, не нужно везде обработку свою делать, есть же общая

Ведь если ошибка есть, она для нас фатальная и не должна обрабатываться, приложение должно упасть и мы это увидим и исправим.

У нас также активно Invoker активно используется при ошибке DEFICIENCY_POINTS (152), мы используем баллы клиента по умолчанию и если их не хватает, то переключаем на работу с агентскими баллами (используя костыль в Events::FAIL_REQUEST мы устанавливаем use_operator_units=true)

За RetryStrategyInterface - 👍

**Comment by yethee** [comment]
@Subszerro в ближайшие дни постараюсь добавить новый тег для 5.x версии.

> У нас также активно Invoker активно используется при ошибке DEFICIENCY_POINTS (152), мы используем баллы клиента по умолчанию и если их не хватает, то переключаем на работу с агентскими баллами (используя костыль в Events::FAIL_REQUEST мы устанавливаем use_operator_units=true)

@dmachehin интересный кейс. :) В #35, при текущей реализации, события не отправляются между вызовами API. И есть общая мысль отказаться от хуков в виде событий.

**Comment by Subszerro** [comment]
> @Subszerro в ближайшие дни постараюсь добавить новый тег для 5.x версии.
Очень ждем!

**Comment by yethee** [comment]
@Subszerro добавил новый тег `5.0.0-beta3`. Был обновлен генератор кода (добавлены type-hint для скалярных типов, обновлены PHPDoc), но надеюсь проблем с обратной совместимостью не возникнет.

**Comment by yethee** [comment]
Доступна стабильная версия [`5.0.0`](https://packagist.org/packages/biplane/yandex-direct#5.0.0), где добавлена поддержка PHP 8.
