### ISSUE TITLE
Несоответствие типов в CampaignFundsParam.php и DailyBudget.php

### ISSUE THREAD

**Issue by AntsHere** [biplane/yandex-direct#39]
Методы

CampaignFunds->GetBalance()
CampaignFunds->GetSumAvailableForTransfer()
DailyBudget->GetAmount()

выдают ошибку несоответствия типа:

Fatal error: Uncaught TypeError: Return value of Biplane\YandexDirect\Api\V5\Contract\CampaignFundsParam::getBalance() must be of the type integer, float returned in vendor\biplane\yandex-direct\src\Api\V5\Contract\CampaignFundsParam.php:46

Если убрать ": int", то все работает как надо.

Скорее всего остальные методы из CampaignFundsParam.php и DailyBudget.php тоже могут выдавать подобную ошибку, но у меня они пока не используются.

**Comment by yethee** [comment]
В расширении soap по умолчанию `xsd:long` конвертируется в `float`, для совместимости с 32-битными платформами.

**Comment by yethee** [comment]
@AntsHere какая версия PHP?

Если в терминале выполнить следующую команду, какой будет результат?

```
$ php -r 'echo PHP_INT_SIZE . PHP_EOL;'
```

**Comment by AntsHere** [comment]
Версия - php-7.1.9-Win32-VC14-x86

Попробовал запустить на php-7.4.9-Win32-vc15-x86, выдал ошибку:
```
Fatal error: Uncaught Error: Undefined constant 'SOAP_COMPRESSION_ACCEPT' in vendor\biplane\yandex-direct\src\Config\SoapOptions.php:28
Stack trace:
#0 vendor\biplane\yandex-direct\src\Config\SoapOptions.php(34): Biplane\YandexDirect\Config\SoapOptions->__construct()
#1 vendor\biplane\yandex-direct\src\Config.php(138): Biplane\YandexDirect\Config\SoapOptions::default()
#2 vendor\biplane\yandex-direct\src\Config.php(37): Biplane\YandexDirect\Config->configureOptions(Object(Symfony\Component\OptionsResolver\OptionsResolver))
#3 vendor\biplane\yandex-direct\src\User.php(90): Biplane\YandexDirect\Config->__construct(Array)
#4 _lib.php(26): Biplane\YandexDirect\User->__construct(Array)
#5 main.php(6): require_o in vendor\biplane\yandex-direct\src\Config\SoapOptions.php on line 28
```

**Comment by yethee** [comment]
Причина в 32-bit. Нет возможности использовать 64-битную версию PHP?
Есть планы, чтобы отказаться от поддержки 32-битной версии PHP. То есть, в composer будет `php-64bit`.

Касательно ошибки с константой. Вероятно, не установлено расширение `soap`. Проверить можно с помощью,

```
$ composer check-platform-reqs
```

**Comment by AntsHere** [comment]
> Касательно ошибки с константой. Вероятно, не установлено расширение `soap`. Проверить можно с помощью,
Да, точно, забыл включить.

> Причина в 32-bit. Нет возможности использовать 64-битную версию PHP?
> Есть планы отказаться от поддержки 32-битной версии PHP. То есть, в composer будет `php-64bit`.
В целом, понятно. У меня на локальном сервере стоит Apache 32 битный, поэтому вначале надо будет заменить его.

**Comment by yethee** [comment]
Начиная с версии 5.1 в `composer.json` явно указано требование 64-битной версии PHP.

Не хочется в type-hints добавлять что-то вроде `float|int|null`, так как это сделает сигнатуры методов в контрактах данных менее понятными. Так же, это приведет к необходимости писать дополнительный код, для приведения типов и т.п, при использовании статического анализатора кода (phpstan, psalm и пр.) в проекте.

Если нужна неявная поддержка 32-битной версии, можно продолжить использовать версию 4.x. В течении какого-то времени в предыдущей версии будут синхронизироваться сервисы и DTO, при изменениях в API.
