### ISSUE TITLE
FilterItem::create typehint поддержка array<int>

### ISSUE THREAD

**Issue by dmachehin** [biplane/yandex-direct#44]
Сейчас для 3-го параметра $values указан typehint `@param array<string>|string $values`, удобнее было бы сделать `@param array<string|int>|string $values`

Чтобы работало так:
`FilterItem::create(FieldEnum::CLICKS, FilterOperatorEnum::GREATER_THAN, [5]);`

**Comment by yethee** [comment]
Сейчас type-hint указан в соответствии со спецификацией отчета (схемой [reports.xsd](https://api.direct.yandex.com/v5/reports.xsd)).
Можно, конечно, изменить на `array<string|int>|string|int`, но это будет частный случай.

При миграции с 4 версии на одном из проектов решил этот вопрос помощью `array_map('strval', [5])`
