### ISSUE TITLE
Проблема с AccountManagementRequest

### ISSUE THREAD

**Issue by AntsHere** [biplane/yandex-direct#46]
Здравствуйте! Не могу понять. Есть такой код:

> $criteria = AccountSelectionCriteria::create()->setAccountIDS([123]);
> $payload = AccountManagementRequest::create()->setSelectionCriteria($criteria)->setAction('Get');
> $response = $USER->getApiService()->accountManagement($payload);

Все работает отлично! Но как только добавляю в массив второй ID (456):

> $criteria = AccountSelectionCriteria::create()->setAccountIDS([123, 456]);

то получаю ошибку:

`Fatal error: Uncaught SoapFault: Параметры запроса указаны неверно`

Тоже самое касается setLogins:

> $criteria = AccountSelectionCriteria::create()->setLogins(['acc1', 'acc2']);

Пока указан один логин, все отлично. Как только добавляю второй - ошибка.

Я документации Яндекса указано, что можно указывать до 100 ID и до 50 логинов ( https://yandex.ru/dev/direct/doc/dg-v4/live/AccountManagement_Get.html ).

В чем может быть ошибка?

**Comment by AntsHere** [comment]
Версия библиотеки то же последняя - 5.4.1. Пробовал и так и эдак, все равно ошибка. Можно указать один ID (любой случайный), ответ будет получен штатно, сообщающий, что такой ID не найден. Добавляю второй (можно точно такой же, можно другой случайный), сразу ошибка SoapFault.

Возможно, что-то не так с моим аккаунтом в самом Яндексе. У меня простой аккаунт (не агентство), которому выдан доступ другого аккаунта. Возможно, проблема в этом.

Но по одиночке я данные по аккаунтам получать могу. Странная штука...

**Comment by yethee** [comment]
В метод `setAccountIDS` или `setLogins` передается индексный массив?

По идее, тип исключения должен быть `Biplane\YandexDirect\Exception\ApiException`, а не `SoapFault`.

Можете попробовать опубликовать XML запроса к API, может это прояснит ситуацию. Только предварительно отредактируйте его (удалите id, логины). 
Данные можно получить с помощью метода `getLastRequest()`. HTTP заголовки не нужны.

```php
$service = $USER->getApiService();

try {  
    $response = $service->accountManagement($payload);
} finally {
    echo $service->getLastRequest();
}
```

**Comment by AntsHere** [comment]
Да, данные передаю в виде простого массива. Для получения ответа, который идет ниже, был передан массив [111, 222]. Если оставить только что-то одно, то будет получен нормальные ответ, что доступа к этому ID нет. Как только добавляю еще один, сразу ошибка.

```
POST /live/v4/soap/ HTTP/1.1
Host: soap.direct.yandex.ru
Connection: close
User-Agent: PHP-SOAP/7.1.9
Accept-Encoding: gzip, deflate
Content-Type: text/xml; charset=utf-8
SOAPAction: "API#AccountManagement"
Content-Length: 1110

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="API" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Header><ns1:locale>ru</ns1:locale><ns1:token>xxx</ns1:token></SOAP-ENV:Header><SOAP-ENV:Body><ns1:AccountManagement><params xsi:type="ns1:AccountManagementRequest"><Action xsi:type="xsd:string">Get</Action><SelectionCriteria xsi:type="ns1:AccountSelectionCriteria"><Logins xsi:nil="true"/><AccountIDS SOAP-ENC:arrayType="xsd:int[2]" xsi:type="ns1:ArrayOfInteger"><item xsi:type="xsd:int">111</item><item xsi:type="xsd:int">222</item></AccountIDS></SelectionCriteria><Payments xsi:nil="true"/><Transfers xsi:nil="true"/><Accounts xsi:nil="true"/><PayMethodID xsi:nil="true"/><CustomTransactionID xsi:nil="true"/><Version xsi:nil="true"/></params></ns1:AccountManagement></SOAP-ENV:Body></SOAP-ENV:Envelope>
```

Кстати, есть еще такая мысль. У меня сейчас аккаунт, в котором нет общего счета, к нему подключен аккаунт, у которого есть общий счет. Возможно, ошибка связана с тем, что всего общих счетов - 1 штука. Но в любом случае это странно, так как ошибка на уровне протокола обмена данными.

**Comment by yethee** [comment]
Закрываю issue, так как проблема не на уровне библиотеки, судя по всему.

Если появятся новые данные, можем открыть issue заново.
