### ISSUE TITLE
Новый закон маркировки рекламы

### ISSUE THREAD

**Issue by madmages** [biplane/yandex-direct#47]
![image](https://user-images.githubusercontent.com/5528679/185593794-c4ff13fd-d7fc-4e9b-9641-15b225c5e3e5.png)
Сегодня яндекс прислал.

Посмотрел на http://api.direct.yandex.com/v5/agencyclients , там появились поле AddRequest.TinInfo которое пока не обязательное. 
Этого поля нет в последних версиях этого пакета.
Было бы клево перегенерить типы.

**Comment by yethee** [comment]
Добавил новый тег. Версия `5.5.0` совместима с последними изменениями в API Яндекс.Директа.

**Comment by madmages** [comment]
огнище!
