### ISSUE TITLE
Когда будет поддержка статистики?

### ISSUE THREAD

**Issue by Delimer** [biplane/yandex-direct#5]
В документации уже появилось https://tech.yandex.ru/direct/doc/reports/reports-docpage/
Когда вы реализуете данный функционал?

**Comment by yethee** [comment]
Пока сложно сказать, сейчас ни в одном из проектов не используется новый API для отчётов.

Как будет свободное время, посмотрю что можно сделать.

**Comment by yethee** [comment]
Добавлена поддержка API для работы с отчётами. Тег `4.1.0-beta1`. Документации пока нет, в реализации может что-то поменяться.

Пример, актуальный для `4.1.0-beta1`:

```php
<?php

use Biplane\YandexDirect\Api\V5\Report\DateRangeTypeEnum;
use Biplane\YandexDirect\Api\V5\Report\FieldEnum;
use Biplane\YandexDirect\Api\V5\Report\ReportDefinitionBuilder;
use Biplane\YandexDirect\Api\V5\Report\ReportTypeEnum;
use Biplane\YandexDirect\User;

$user = new User([
    'access_token' => 'INSERT_YOUR_ACCESS_TOKEN',
    'login' => 'CLIENT_LOGIN',
]);

$service = $user->getReportsService();

$reportDefinitionBuilder = (new ReportDefinitionBuilder())
    ->setReportName('my report')
    ->setReportType(ReportTypeEnum::ACCOUNT_PERFORMANCE_REPORT)
    ->setDateRangeType(DateRangeTypeEnum::LAST_14_DAYS)
    ->setFieldNames([
        FieldEnum::CAMPAIGN_TYPE,
        FieldEnum::IMPRESSIONS,
        FieldEnum::CLICKS,
        FieldEnum::COST,
    ]);

$service->download('path/to/report.tsv', $reportDefinitionBuilder);
```

В данном случае скрипт будет отправлять запросы к серверу API пока не будет готов отчёт, с интервалом согласно заголовку [retryIn](https://tech.yandex.ru/direct/doc/reports/headers-docpage/#retryIn). По готовности отчёт будет сохранён в файл `path/to/report.tsv`.

Если с данными нужно работать сразу, не сохраняя на диск, можно использовать метод `getReady`:

```php
$result = $service->getReady($reportDefinitionBuilder);
echo $result->getData();
```

Если  нужно проверить статус (готов к загрузке или нет) отчёта, то есть метод `get`. В этом случае будет выполнен только один запрос к серверу API:

```php
$result = $service->get($reportDefinitionBuilder);

if ($result->isReady()) {
    echo $result->getData(); // или $result->save('path/to/report.tsv')
} else {
    echo 'Отчёт ещё не сформирован.';
}
```

**Comment by Delimer** [comment]
Спасибо!
