### ISSUE TITLE
Добавление представителей

### ISSUE THREAD

**Issue by ctapu4ok** [biplane/yandex-direct#54]
В библиотеке есть упоминание о функционале 
Biplane\YandexDirect\Api\V5\Contract\Representative
То-есть это своего рода добавление представителей в YD? В API яндекс директа не описан пример обновления, в библиотеке я так же не увидел связей с ним.

Данное АПИ еще не реализовано на стороне яндекса? Есть ли пример, как через AgencyClients добавить нового представителя для клиента?

**Comment by ctapu4ok** [comment]
Пример кода:

```
 $serviceFactory = new ApiServiceFactory();
        $config = ConfigBuilder::create()->
        setAccessToken('12345')->
        setClientLogin('qwewqewqe')->
        setLocale('ru')
            ->getConfig();

        $service = $serviceFactory->createService($config, AgencyClients::class);


        $UpdateAgencyCLients = Contract\UpdateAgencyClientsRequest::create();

         $Representives = Contract\Representative::create()->setEmail('dev-login123will@yandex.ru')
             ->setLogin('dev-login123will')
             ->setRole(Contract\RepresentativeRoleEnum::READONLY);


        $clients[] = Contract\ClientGetItem::create()->setClientId(12345)->setRepresentatives([$Representives]);


        $UpdateAgencyCLients->setClients($clients);

        $response = $service->update($UpdateAgencyCLients);

        dd($response);
```
В ответ получаю ошибку:

  Некорректный запрос: Элемент массива Clients содержит неизвестный параметр type

**Comment by yethee** [comment]
> Пример кода:

Код не корректен. Метод `UpdateAgencyClientsRequest::setClients()` принимает массив [`AgencyClientUpdateItem`](https://github.com/biplane/yandex-direct/blob/c76a83a1e56e0454a2924178d017bf9f28a1466c/src/Api/V5/Contract/AgencyClientUpdateItem.php), вы же передаете массив объектов [`ClientGetItem`](https://github.com/biplane/yandex-direct/blob/c76a83a1e56e0454a2924178d017bf9f28a1466c/src/Api/V5/Contract/ClientGetItem.php).
