### ISSUE TITLE
Добавьте поддержку psr log v2/3

### ISSUE THREAD

**Issue by rik43** [biplane/yandex-direct#55]
Без этого ваши модули не ставятся на современные фреймворки.
composer.json
```
"psr/log": "^1|^2|^3",
```

**Comment by yethee** [comment]
Сейчас нет явной зависимости от `psr/log`, composer [requires](https://github.com/biplane/yandex-direct/blob/c76a83a1e56e0454a2924178d017bf9f28a1466c/composer.json#L17-L27).

Можно с помощью команды `composer why` посмотреть какие пакеты явно зависят от `psr/log` и с какими версиями совместимы.

```cmd
$ composer why psr/log
```

**Comment by rik43** [comment]
есть 
```json
  "require-dev": {
    // ...
    "psr/log": "^1.1",
    // ....
  },
```

**Comment by yethee** [comment]
Зависимости из `require-dev` ([документация](https://getcomposer.org/doc/04-schema.md#require-dev)) игнорируются, когда файл `composer.json` не в корневой директории проекта.

У меня есть проекты, где в зависимостях `biplane/yandex-direct: ^5.0`, и никаких проблем с `psr/log`.

![image](https://github.com/biplane/yandex-direct/assets/559488/ba49bd40-96cd-4ba7-b783-76761d16c677)

**Comment by yethee** [comment]
Так же можно воспользоваться командой `why-not`, чтобы посмотреть какие пакеты не совместимы с нужной версией `psr/log`.

```cmd
$ composer why-not psr/log 2.0
```
или
```cmd
$ composer why-not psr/log 3.0
```
