### ISSUE TITLE
Обновление моделей

### ISSUE THREAD

**Issue by dmachehin** [biplane/yandex-direct#56]
> В методы сервисов [Bids](https://yandex.ru/dev/direct/doc/ref-v5/bids/bids.html), [KeywordBids](https://yandex.ru/dev/direct/doc/ref-v5/keywordbids/keywordbids.html) и [Keywords](https://yandex.ru/dev/direct/doc/ref-v5/keywords/keywords.html) добавлено поле AutotargetingSearchBidIsAuto – признак включения [автоматической ставки](https://yandex.ru/support/direct/impression-criteria/autotargeting.html#autotargeting__auto-bids).

Хорошо бы обновить схемы до актуальной версии

**Comment by yethee** [comment]
В новой версии, `5.9.0`, сервисы совместимы с последними изменениями в API.
