### ISSUE TITLE
При запросе одиночного объекта, возвращается не массив, а сам объект

### ISSUE THREAD

**Issue by Userdestroyer** [biplane/yandex-direct#58]
Добрый день!
Наблюдается ошибка при получении одиночных записей, в том числе и их ошибок, когда вместо массива объектов/ошибок, если запись одна, возврвщается экземпляр объекта вместо массива.
Пример, запрос **Biplane\YandexDirect\Api\V5\AdGroups::update()**, когда количество **AdGroupUpdateItem[]** в массиве две штуки:

```
Biplane\YandexDirect\Api\V5\Contract\UpdateAdGroupsResponse^ {#1438
  #UpdateResults: array:2 [
    0 => Biplane\YandexDirect\Api\V5\Contract\ActionResult^ {#1460
      +"Id": 4540733
    }
    1 => Biplane\YandexDirect\Api\V5\Contract\ActionResult^ {#1459
      +"Id": 4540734
    }
  ]
} 

```

Когда в массиве **AdGroupUpdateItem[]** одна штука:

```
Biplane\YandexDirect\Api\V5\Contract\UpdateAdGroupsResponse^ {#1437
  #UpdateResults: Biplane\YandexDirect\Api\V5\Contract\ActionResult^ {#1459
    +"Id": 4540733
  }
}
```

Соответственно от этого ломаются встроенные методы вроде **getUpdateResults()**, поскольку тот должен вернуть array, но у нас объект. То же самое наблюдается на всех объектах Директа, при получении одиночной записи - Campaigns, Ads, и прочие.
Даже при получении ошибки, там не содержится массив с 1 ошибкой, а объект.
Версию обновил с 5.8.1 до 5.11.0, ошибка сохраняется.
По сути я понимаю, что в документации яндекса указано возвращение массивов в любом случае, даже в одиночном, и вроде как ответ от сервера выглядит нормально. В чем может заключаться проблема?
Примеры SOAP:
Запрос на 2 объекта:
```
<SOAP-ENV:Envelope
	xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP-ENV:Header/>
	<SOAP-ENV:Body>
		<ns3:UpdateResponse
			xmlns:ns3="http://api.direct.yandex.com/v5/adgroups"
			xmlns="">
			<UpdateResults>
				<Id>4540733</Id>
			</UpdateResults>
			<UpdateResults>
				<Id>4540734</Id>
			</UpdateResults>
		</ns3:UpdateResponse>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
Запрос на 1 объект:
```
<SOAP-ENV:Envelope
	xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP-ENV:Header/>
	<SOAP-ENV:Body>
		<ns3:UpdateResponse
			xmlns:ns3="http://api.direct.yandex.com/v5/adgroups">
			<UpdateResults>
				<Id>4540733</Id>
			</UpdateResults>
		</ns3:UpdateResponse>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope> 
```
Пример запроса с ошибкой (ошибка тоже ломает метод **Biplane\YandexDirect\Api\V5\Contract\ActionResultBase::getErrors()**, т.к. объект **ExceptionNotification**, а не массив ):
```
<SOAP-ENV:Envelope
	xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP-ENV:Header/>
	<SOAP-ENV:Body>
		<ns3:UpdateResponse
			xmlns:ns3="http://api.direct.yandex.com/v5/adgroups">
			<UpdateResults>
				<Id>4540733</Id>
			</UpdateResults>
			<UpdateResults>
				<Errors>
					<Code>8800</Code>
					<Message>Объект не найден</Message>
					<Details>Группа объявлений не найдена</Details>
				</Errors>
			</UpdateResults>
		</ns3:UpdateResponse>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

**Comment by Userdestroyer** [comment]
Ответ нашел, кому может быть полезно:
При вызове клиента в массив $options добавил `'features' => SOAP_SINGLE_ELEMENT_ARRAYS` , например
`new Biplane\YandexDirect\Api\V5\AdGroups($config, [ 'features' => SOAP_SINGLE_ELEMENT_ARRAYS ])`

**Comment by yethee** [comment]
Привет!

За сериализацию/десериализацию отвечает расширение [SOAP](https://www.php.net/manual/en/book.soap.php). Какая версия PHP и расширения SOAP используется?

Ни разу с подобной ошибкой не сталкивался и сейчас воспроизвести не удалось.
Например, ответ,

```xml
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header />
  <SOAP-ENV:Body>
    <ns3:AddResponse xmlns:ns3="http://api.direct.yandex.com/v5/sitelinks">
      <AddResults>
        <Warnings>
          <Code>10120</Code>
          <Message>Указанный набор быстрых ссылок дублирует ранее созданный набор</Message>
        </Warnings>
        <Id>1297715838</Id>
      </AddResults>
    </ns3:AddResponse>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
успешно маппится на PHP структуры, согласно WSDL:

<details>
  <summary>Show print_r()</summary>

  Output:

```
Biplane\YandexDirect\Api\V5\Contract\AddSitelinksResponse Object
(
    [AddResults] => Array
        (
            [0] => Biplane\YandexDirect\Api\V5\Contract\ActionResult Object
                (
                    [Warnings] => Array
                        (
                            [0] => Biplane\YandexDirect\Api\V5\Contract\ExceptionNotification Object
                                (
                                    [Code:protected] => 10120
                                    [Message:protected] => Указанный набор быстрых ссылок дублирует ранее созданный набор
                                )
                        )
                    [Id] => 1297715838
                )
        )
)
```
</details>

[Тут](https://github.com/biplane/yandex-direct/commit/a59eb22050b0f16f339b043be4bab4cf97bcea03) весь код теста. Можно локально проверить, если есть желание.
PS: На тело запроса можно не обращать внимания, он фейковый. А ответ (xml контент) взят из логов реального приложения.

**Comment by yethee** [comment]
@Userdestroyer да, причина во флаге `SOAP_SINGLE_ELEMENT_ARRAYS`.

Если сервисы создавать через фабрику (`Biplane\YandexDirect\ApiServiceFactory`), как предполагается по умолчанию :), то такой проблемы с совместимостью не нужно будет решать самостоятельно.
