### ISSUE TITLE
Спарсить TSV репорта

### ISSUE THREAD

**Issue by Extalionez** [biplane/yandex-direct#59]
Я, конечно, всё понимаю - сохранять в файл это самое простое. А как спарсить-то этот tsv файл в массив/объект?

**Comment by yethee** [comment]
Это уже зависит от проекта. Например,

* [`fgetcsv`](https://www.php.net/manual/en/function.fgetcsv.php)
* [`league/csv`](https://github.com/thephpleague/csv)
* [`loophp/collection`](https://loophp-collection.readthedocs.io/en/latest/pages/api.html#fromfile)

PS: Объем данных может быть большим, поэтому парсить весь файл в массив может быть не оптимальным решением. Поэтому, лучше сразу рассматривать логику с потоковой обработкой, через генераторы.
