### ISSUE TITLE
Invalid type hint for AdImageAddItem::setImageData()

### ISSUE THREAD

**Issue by okwinza** [biplane/yandex-direct#6]
https://github.com/biplane/yandex-direct/blob/11fe5a46e3814fd22fe02cb5b17ca1fb6c38bf9d/src/Api/V5/Contract/AdImageAddItem.php#L41

Похоже на баг в генераторе, т.к. по идее это должен быть обычный примитив без тайпхинта.

**Comment by yethee** [comment]
Спасибо.

Исправил. Изменения доступны в master-е.
