### ISSUE TITLE
TextAdUpdate

### ISSUE THREAD

**Issue by yurkoi83** [biplane/yandex-direct#7]
Есть необходимость обновить только два параметра:
Title2 и Href, передаем только их.
В случае когда DisplayUrlPath не заполнен, он принимает такой вид:
store.ru/NIL /

**Comment by yethee** [comment]
Может это проблема в интерфейсе Я.Директа?

Если метод `TextAdUpdate::setDisplayUrlPath()` не вызывался или при вызове был передан `null`, то клиент отправит корректное значение для поля `DisplayUrlPath`.

После успешного обновления объявления если запросить данные через API, то поле `DisplayUrlPath` по прежнему будет содержать значение `null`.

**Comment by yethee** [comment]
Вопрос был задан в тех. поддержку Я.Директа. Говорят, что-то исправили на своей стороне и что сейчас проблемы с  Nil не должно быть.

**Comment by yurkoi83** [comment]
Круто, спасибо буду пробовать!
